### ISSUE TITLE
Hardware requirements: CUDA out of memory error while training

### ISSUE THREAD

**Issue by bouzaien** [facebookresearch/vilbert-multi-task#50]
Hello,

Following the multi-task training instructions, I used ```python train_tasks.py --bert_model bert-base-uncased --from_pretrained save/multi_task_model.bin --config_file config/bert_base_6layer_6conect.json --tasks 1 --lr_scheduler 'warmup_linear' --train_iter_gap 4 --task_specific_tokens --save_name multi_task_model_0``` in order to train the base model for the VQA task.

I am using a single 4-GB GPU with the following characteristic:
![Screenshot from 2020-07-17 11-16-24](https://user-images.githubusercontent.com/31316601/87789422-52733c00-c83f-11ea-966d-023ef5512e79.png)

When I start training, I am running into the following issue: `RuntimeError: CUDA out of memory. Tried to allocate 52.00 MiB (GPU 0; 3.94 GiB total capacity; 3.28 GiB already allocated; 48.31 MiB free; 3.39 GiB reserved in total by PyTorch)`. I also tried to reduce the `batch_size` for `TASK1` in the `vilbert_tasks.yml` file to use less memory, but the error persists.

Could anyone provide the minimum hardware requirements to train the model for a specific task (e.g., `VQA`)?

Here is a full discription of the error:
```07/17/2020 08:39:33 - INFO - __main__ -   device: cuda n_gpu: 1, distributed training: False, 16-bits training: False
07/17/2020 08:39:34 - INFO - pytorch_transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/aloui/.cache/torch/pytorch_transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
07/17/2020 08:39:34 - INFO - vilbert.task_utils -   Loading VQA Dataset with batch size 128
07/17/2020 08:39:34 - INFO - vilbert.datasets.vqa_dataset -   Loading from datasets/VQA/cache/VQA_trainval_23_cleaned.pkl
07/17/2020 08:41:46 - INFO - vilbert.datasets.vqa_dataset -   Loading from datasets/VQA/cache/VQA_minval_23_cleaned.pkl
07/17/2020 08:41:46 - INFO - vilbert.utils -   logging file at: save/VQA_bert_base_6layer_6conect-multi_task_model_0/logs
07/17/2020 08:41:46 - INFO - vilbert.utils -   loading weights file save/multi_task_model.bin
559 559
***** Running training *****
  Num Iters:  {'TASK1': 4236}
  Batch size:  {'TASK1': 128}
  Num steps: 84720
Epoch:   0%|                                                |0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_tasks.py", line 673, in <module>
    main()
  File "train_tasks.py", line 533, in main
    task_losses,
  File "/aloui/vilbert-multi-task/vilbert/task_utils.py", line 321, in ForwardModelsTrain
    task_tokens,
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/aloui/vilbert-multi-task/vilbert/vilbert.py", line 1662, in forward
    output_all_attention_masks=output_all_attention_masks,
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/aloui/vilbert-multi-task/vilbert/vilbert.py", line 1387, in forward
    output_all_attention_masks=output_all_attention_masks,
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/aloui/vilbert-multi-task/vilbert/vilbert.py", line 1065, in forward
    use_co_attention_mask,
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/aloui/vilbert-multi-task/vilbert/vilbert.py", line 895, in forward
    layer_output1 = self.v_output(intermediate_output1, attention_output1)
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/aloui/vilbert-multi-task/vilbert/vilbert.py", line 676, in forward
    hidden_states = self.dropout(hidden_states)
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/dropout.py", line 54, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/home/aloui/miniconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/functional.py", line 807, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: CUDA out of memory. Tried to allocate 52.00 MiB (GPU 0; 3.94 GiB total capacity; 3.28 GiB already allocated; 46.81 MiB free; 3.39 GiB reserved in total by PyTorch)
```

**Comment by claire43** [comment]
Same here, with a slightly different stack trace. Was trying to fine-tune on RefCOCO. 
pytorch==1.4.0, cuda 10.0

> ***** Running training *****                                                                                                                                                                                
  Num Iters:  {'TASK9': 96221}                                                                                                                                                                              
  Batch size:  {'TASK9': 1}                                                                                                                                                                                 
  Num steps: 1924420                                                                                                                                                                                        
Epoch:   0%|                                                                                                                                                                         | 0/20 [00:00<?, ?it/s$
device: cuda                                                                                                                                                                                                
Warning: Traceback of forward call that caused the error:                                                                                                                                                   
  File "train_tasks.py", line 688, in <module>                                                                                                                                                              
    main()                                                                                                                                                                                                  
  File "train_tasks.py", line 548, in main                                                                                                                                                                  
    task_losses,                                                                                                                                                                                            
  File "/phoenix/S7/yc2296/data/people_grounding/vilbert_mt/vilbert/task_utils.py", line 321, in ForwardModelsTrain                                                                                         
    task_tokens,                                                                                                                                                                                            
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                                                                               
    result = self.forward(*input, **kwargs)                                                                                                                                                                 
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward                                                                        
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])                                                                                                                                   
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 156, in replicate                                                                      
    return replicate(module, device_ids, not torch.is_grad_enabled())                                                                                                                                       
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 88, in replicate                                                                           
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)                                                                                                                                    
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape                                                        
    tensor_copies = Broadcast.apply(devices, *tensors)                                                                                                                                                      
 (print_stack at /opt/conda/conda-bld/pytorch_1579027003190/work/torch/csrc/autograd/python_anomaly_mode.cpp:57)                   

> Traceback (most recent call last):                                                                                                                                                                          
  File "train_tasks.py", line 688, in <module>                                                                                                                                                              
    main()                                                                                                                                                                                                  
  File "train_tasks.py", line 555, in main                                                                                                                                                                  
    loss.backward()                                                                                                                                                                                         
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward                                                                                          
    torch.autograd.backward(self, gradient, retain_graph, create_graph)                                                                                                                                     
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward                                                                                
    allow_unreachable=True)  # allow_unreachable flag                                                                                                                                                       
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/autograd/function.py", line 77, in apply                                                                                   
    return self._forward_cls.backward(self, *args)                                                                                                                                                          
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 32, in backward                                                                           
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)                                                                                                              
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 43, in forward                                                                            
    return comm.reduce_add_coalesced(grads, destination)                                                                                                                                                    
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/cuda/comm.py", line 121, in reduce_add_coalesced                                                                           
    flat_result = reduce_add(flat_tensors, destination)                                                                                                                                                     
  File "/home/yc2296/anaconda3/envs/vilbert-mt/lib/python3.6/site-packages/torch/cuda/comm.py", line 73, in reduce_add
    result = inp.new(device=destination).resize_as_(inp).zero_()
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.93 GiB total capacity; 2.48 GiB already allocated; 18.31 MiB free; 2.73 GiB reserved in total by PyTorch)
                                                                                                                                                                                       

I have tried both decreasing the batch size all the way from 256, 128,..., to 1. 
Also tried `torch.cuda.empty_cache()`.
Neither worked.

**Comment by bouzaien** [comment]
The error persists even when extending GPU to 12GB.

**Comment by bouzaien** [comment]
The problem is solved when using a 12GB GPU **and** reducing the batch size to 64 (instead of 128) in the `vilbert_tasks.yml` file.

**Comment by MitraTj** [comment]
How to use multi-gpus instead?
